sudo: required
services:
  - docker

before_install:
  - docker build -t sustain77/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sustain77/docker-react npm run test -- --coverage